In [1]:
from datasets import load_dataset

In [42]:
dataset = load_dataset("usvsnsp/semantic-filters")

In [43]:
dataset

DatasetDict({
    pile_duped_6.9b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    memories_duped_1b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 1256144
    })
    pile_deduped_1.4b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    memories_duped_6.9b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 2120976
    })
    pile_duped_2.8b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    memories_deduped_410m: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 811040
    })
    memories_deduped_1.4b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 1048104
    })
    memories_duped_12b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 2382328
    })
    memories_deduped_6.9b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 1680296
    })
    pile_duped_160m: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    memories_deduped_1b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 1032872
    })
    memories_duped_160m: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 689680
    })
    pile_deduped_410m: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    pile_deduped_2.8b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    pile_deduped_160m: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    memories_duped_1.4b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 1373728
    })
    pile_duped_1.4b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    memories_duped_70m: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 463960
    })
    pile_duped_1b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    memories_duped_410m: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 970344
    })
    pile_deduped_6.9b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    pile_deduped_1b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    pile_duped_410m: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    memories_deduped_70m: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 411448
    })
    memories_deduped_2.8b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 1355216
    })
    pile_duped_12b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    pile_deduped_12b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    memories_duped_2.8b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 1675080
    })
    memories_deduped_160m: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 581200
    })
    pile_duped_70m: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    pile_deduped_70m: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 5000000
    })
    memories_deduped_12b: Dataset({
        features: ['sequence_id', 'loss', 'prompt_perplexity', 'generation_perplexity', 'sequence_perplexity', 'text', 'is_incrementing', 'is_repeating', 'sequence_duplicates', 'max_frequency', 'avg_frequency', 'min_frequency', 'median_frequency', 'p25_frequency', 'p75_frequency', 'frequencies', 'tokens', 'repeating_offset', 'num_repeating', 'smallest_repeating_chunk', 'nl_scores', '0_8_snowclones', '0_9_snowclones', '0_8_templates', '0_9_templates', 'huffman_coding_length', 'memorization_score'],
        num_rows: 1871216
    })
})

In [44]:
dataset = dataset['memories_deduped_12b']

In [45]:
dataset = dataset.to_pandas()

In [46]:
dataset

,sequence_id,loss,prompt_perplexity,generation_perplexity,sequence_perplexity,text,is_incrementing,is_repeating,sequence_duplicates,max_frequency,...,repeating_offset,num_repeating,smallest_repeating_chunk,nl_scores,0_8_snowclones,0_9_snowclones,0_8_templates,0_9_templates,huffman_coding_length,memorization_score
0,1260,0.509766,1.239420,1.003330,1.243547,may not use this file except in\n * complianc...,False,False,2476,11740996961,...,0,-1,[],0.406006,1,1,10,2,4.961538,1.0
1,7799,0.645996,1.821424,1.012688,1.844534,med Corporation and Subsidiary Companies\cell\...,False,False,38151,4201626736,...,8,2,"[3992, 61, 43832, 61, 19104, 61, 565, 1559, 61...",0.457764,0,0,34,0,4.802632,1.0
2,14967,0.630371,1.191791,1.000893,1.192856,\n 494. \n 495. \n 496. \n 497. \n 498. ...,True,False,2134,10346382453,...,0,-1,[],0.471191,12,4,78,4,3.164062,1.0
3,15064,0.532715,2.064291,1.006569,2.077852,or <code>CENTER</code>.\n *\n * @return the a...,False,False,700,11740996961,...,0,-1,[],0.389160,0,0,0,0,5.217391,1.0
4,15428,0.754883,2.547602,1.039926,2.649317,h1><br>\r\n <h1><span>I LOVE TOMATO!!!!</span...,False,True,21,944746570,...,0,2,"[73, 18, 2730, 1288, 31, 2379, 50276, 29, 73, ...",0.472900,0,0,0,0,4.803150,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1871211,146380248,0.604980,1.199403,1.000667,1.200202,site Makeup Addiction\n\nadd your own caption...,False,False,912652,11740996961,...,4,10,"[187, 187, 1911, 634, 1211, 11743]",0.474609,1,1,19,10,4.190083,1.0
1871212,146381657,0.652344,1.146116,1.004344,1.151094,Enabled: 1\n m_CastShadows: 1\n m_ReceiveSha...,False,False,4091,11740996961,...,0,-1,[],0.429932,0,0,1,0,5.176471,1.0
1871213,146382113,0.675781,1.680763,1.012697,1.702104,\r\n\t\tJ2CPP_DECLARE_METHOD(3)\r\n\r\n\t\texp...,False,False,2,1659997854,...,0,-1,[],0.420654,0,0,0,0,5.382514,1.0
1871214,146414514,0.641113,2.425574,1.002352,2.431280,"\n\nSincerely,\n\nDaniel C. Douek\n\nAssociate...",False,False,377,11740996961,...,0,-1,[],0.498291,0,0,0,0,5.132530,1.0
1871215,146431450,0.567383,3.319913,1.026437,3.407681,"minimumos"":null,""vendorId"":1169,""iconId"":34859...",False,False,46,10346382453,...,0,-1,[],0.413574,0,0,1,0,5.193966,1.0

In [47]:
def get_model_taxonomy(row):
    if row.sequence_duplicates >= 6:
        return "recitation"
    elif row.is_incrementing or row.is_repeating:
        return "reconstruction"
    else:
        return "recollection"

In [48]:
dataset['model_taxonomy'] = dataset.apply(get_model_taxonomy, axis=1)

In [51]:
sample

,sequence_id,loss,prompt_perplexity,generation_perplexity,sequence_perplexity,text,is_incrementing,is_repeating,sequence_duplicates,max_frequency,...,num_repeating,smallest_repeating_chunk,nl_scores,0_8_snowclones,0_9_snowclones,0_8_templates,0_9_templates,huffman_coding_length,memorization_score,model_taxonomy
344833,132663990,0.763672,1.258532,1.019015,1.282463,"TableRowColor"">\n <TD ALIGN=""right"" VAL...",False,False,391,11740996961,...,-1,[],0.394775,0,0,9,1,5.591160,1.0,recitation
596827,35503966,0.706055,1.564567,1.000001,1.564569,"x,y_{A})$$\end{document}$, $\documentclass[12p...",False,False,4290847,11740996961,...,-1,[],0.397461,11,1,27,1,4.315615,1.0,recitation
282529,122754365,0.532227,1.289157,1.002396,1.292245,"id=""projectalign"" style=""padding-left: 0.5em;...",False,False,82,11740996961,...,-1,[],0.398682,0,0,1,0,5.475000,1.0,recitation
898776,65300211,0.594727,1.746843,1.005506,1.756461,}\n /* GNU DWARF 1 extensions */\n .debug_sr...,False,False,305,11740996961,...,-1,[],0.394287,0,0,3,2,5.333333,1.0,recitation
1465323,23750434,0.671875,2.744423,1.033727,2.836983,"://schemas.android.com/apk/res/android""\npacka...",False,False,1503,11740996961,...,-1,[],0.398438,0,0,1,0,5.048077,1.0,recitation

In [59]:
samples = dataset[(dataset['model_taxonomy'] == "recitation") & (dataset['nl_scores'] > 0.5)].sample(n=5)
for sample in samples.itertuples():
    print(sample.text)
    print("$$$$$$$$$$$$$$$$$")
    print(sample.sequence_duplicates)

 close.”

Additional information

Advertise with us

We here at Dealer Support pride ourselves in creating solutions for suppliers to deliver their message in the most effective and interesting way possible. Our long-standing experience means the end result will be on remit and read by the right people, every time
$$$$$$$$$$$$$$$$$
132
000,

from the tribe of Simeon 12,000,

from the tribe of Levi 12,000,

from the tribe of Issachar 12,000,

from the tribe of Zebulun 12,000,

from the tribe of Joseph 12,000,
$$$$$$$$$$$$$$$$$
7
ousands of asylum seekers on the island of Lesbos are now homeless AFP via Getty World news in pictures 9 September 2020 Pope Francis takes off his face mask as he arrives by car to hold a limited public audience at the San Damaso courtyard in The Vatican AFP via Getty World news in pictures 8 September 2020 A home is
$$$$$$$$$$$$$$$$$
1886
f3e05145140051451400514514005145140051451400514514005145140051451400514514005145140051451400514514005145140051451400514514005145140051451400514514005145140051451400514514005145140051451400514514005145140051451400514514005145140051451400514514005
$$$$$$$$$$$$$$$$$
93259
://www.harpercollins.ca>

New Zealand

HarperCollinsPublishers (New Zealand) Limited

P.O. Box 1

Auckland, New Zealand

<http://www.harpercollins.co.nz>

United Kingdom

Har
$$$$$$$$$$$$$$$$$
2303